name: run-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install Node js
        uses: actions/setup-node@v1

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0

      - name: Install dependencies
        run: npm install

      - name: Run test cases
        run: npm run test
        env:
          DATABASE_URL: mongodb://localhost/todoapp
          ACCESS_TOKEN_SECRET: lolnosecret
